### ISSUE TITLE
Problems with levels

### ISSUE THREAD

**Issue by deanishe** [xilopaint/alfred-things#14]
The workflow doesn't find projects at the top-level (i.e. not in an area), nor todos in projects (i.e. Area > Project > Todo).

Would you consider also including these items?

**Comment by xilopaint** [comment]
> The workflow doesn't find projects at the top-level

It's not something simple to implement, if it's possible, since the first action is aimed to display and interact with lists. Areas are handled as lists by the API, but not projects. I would gladly accept a PR here. AppleScript is nasty and Things API is not particularly great.

> nor todos in projects (i.e. Area > Project > Todo)

This was already implemented, you just need to use `⇧ + ↩`. I just updated README to mention this action.

**Comment by deanishe** [comment]
> This was already implemented.

Thanks!

> Things API is not particularly great.

It's shit, tbh. I found a bug and reported it to Cultured Code. They basically said, "we know and we don't care."

> Applescript is nasty

Why are you using AppleScript? I mean JXA isn't much better, but at least it supports JSON.

**Comment by xilopaint** [comment]
> Why are you using AppleScript? I mean JXA isn't much better, but at least it supports JSON.

Sorry for the late reply. We both had a discussion about this issue [here](https://www.alfredforum.com/topic/10978-applescript-vs-jxa/).
